### ISSUE TITLE
RegExp 1

### ISSUE THREAD

**Issue by fabiosalvi** [Codemantic/satorarepo#9]
Take this book:
http://www.allitebooks.com/introducing-regular-expressions-2/

You can download from there.

- [x] Read Chapter 1
- [x] Make a honest assessment about "Did I understand Chapter 1"?
- [x] Whatever the outcome of the previous, read Chapter 2.
- [x] Stop and digest.
- [x] If necessary, iterate over Chapter 1 and 2

**Comment by francescomiano** [comment]
Per me va bene fermarmi ai primi due capitoli.
